//  File implement/oglplus/enums/query_target_names.ipp
//
//  Automatically generated file, DO NOT modify manually.
//  Edit the source 'source/enums/oglplus/query_target.txt'
//  or the 'source/enums/make_enum.py' script instead.
//
//  Copyright 2010-2015 Matus Chochlik.
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
//
namespace enums {
OGLPLUS_LIB_FUNC CStrRef ValueName_(
	QueryTarget*,
	GLenum value
) noexcept
#if (!OGLPLUS_LINK_LIBRARY || defined(OGLPLUS_IMPLEMENTING_LIBRARY)) && \
	!defined(OGLPLUS_IMPL_EVN_QUERYTARGET)
#define OGLPLUS_IMPL_EVN_QUERYTARGET
{
switch(value)
{
#if defined GL_TIME_ELAPSED
	case GL_TIME_ELAPSED: return CStrRef("TIME_ELAPSED");
#endif
#if defined GL_TIMESTAMP
	case GL_TIMESTAMP: return CStrRef("TIMESTAMP");
#endif
#if defined GL_SAMPLES_PASSED
	case GL_SAMPLES_PASSED: return CStrRef("SAMPLES_PASSED");
#endif
#if defined GL_ANY_SAMPLES_PASSED
	case GL_ANY_SAMPLES_PASSED: return CStrRef("ANY_SAMPLES_PASSED");
#endif
#if defined GL_PRIMITIVES_GENERATED
	case GL_PRIMITIVES_GENERATED: return CStrRef("PRIMITIVES_GENERATED");
#endif
#if defined GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN
	case GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN: return CStrRef("TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN");
#endif
#if defined GL_VERTICES_SUBMITTED_ARB
	case GL_VERTICES_SUBMITTED_ARB: return CStrRef("VERTICES_SUBMITTED_ARB");
#endif
#if defined GL_PRIMITIVES_SUBMITTED_ARB
	case GL_PRIMITIVES_SUBMITTED_ARB: return CStrRef("PRIMITIVES_SUBMITTED_ARB");
#endif
#if defined GL_VERTEX_SHADER_INVOCATIONS_ARB
	case GL_VERTEX_SHADER_INVOCATIONS_ARB: return CStrRef("VERTEX_SHADER_INVOCATIONS_ARB");
#endif
#if defined GL_TESS_CONTROL_SHADER_PATCHES_ARB
	case GL_TESS_CONTROL_SHADER_PATCHES_ARB: return CStrRef("TESS_CONTROL_SHADER_PATCHES_ARB");
#endif
#if defined GL_TESS_EVALUATION_SHADER_INVOCATIONS_ARB
	case GL_TESS_EVALUATION_SHADER_INVOCATIONS_ARB: return CStrRef("TESS_EVALUATION_SHADER_INVOCATIONS_ARB");
#endif
#if defined GL_GEOMETRY_SHADER_INVOCATIONS
	case GL_GEOMETRY_SHADER_INVOCATIONS: return CStrRef("GEOMETRY_SHADER_INVOCATIONS");
#endif
#if defined GL_GEOMETRY_SHADER_PRIMITIVES_EMITTED_ARB
	case GL_GEOMETRY_SHADER_PRIMITIVES_EMITTED_ARB: return CStrRef("GEOMETRY_SHADER_PRIMITIVES_EMITTED_ARB");
#endif
#if defined GL_FRAGMENT_SHADER_INVOCATIONS_ARB
	case GL_FRAGMENT_SHADER_INVOCATIONS_ARB: return CStrRef("FRAGMENT_SHADER_INVOCATIONS_ARB");
#endif
#if defined GL_COMPUTE_SHADER_INVOCATIONS_ARB
	case GL_COMPUTE_SHADER_INVOCATIONS_ARB: return CStrRef("COMPUTE_SHADER_INVOCATIONS_ARB");
#endif
#if defined GL_CLIPPING_INPUT_PRIMITIVES_ARB
	case GL_CLIPPING_INPUT_PRIMITIVES_ARB: return CStrRef("CLIPPING_INPUT_PRIMITIVES_ARB");
#endif
#if defined GL_CLIPPING_OUTPUT_PRIMITIVES_ARB
	case GL_CLIPPING_OUTPUT_PRIMITIVES_ARB: return CStrRef("CLIPPING_OUTPUT_PRIMITIVES_ARB");
#endif
#if defined GL_TRANSFORM_FEEDBACK_OVERFLOW_ARB
	case GL_TRANSFORM_FEEDBACK_OVERFLOW_ARB: return CStrRef("TRANSFORM_FEEDBACK_OVERFLOW_ARB");
#endif
#if defined GL_TRANSFORM_FEEDBACK_STREAM_OVERFLOW_ARB
	case GL_TRANSFORM_FEEDBACK_STREAM_OVERFLOW_ARB: return CStrRef("TRANSFORM_FEEDBACK_STREAM_OVERFLOW_ARB");
#endif
	default:;
}
OGLPLUS_FAKE_USE(value);
return CStrRef();
}
#else
;
#endif
} // namespace enums

